### ISSUE TITLE
cmake为啥编译不出来assimp-vc120-mt.lib

### ISSUE THREAD

**Issue by louiskoo520** [a120471/CG2Assignment3Qt#1]
![image](https://cloud.githubusercontent.com/assets/4961164/21916345/e836f720-d97a-11e6-89a3-2498d54470f9.png)

**Comment by a120471** [comment]
assimp-vc120-mt.lib是assimp库的文件，是通过编译assimp项目得到的。
除了assimp，这个工程应该还用到了glm库，stb_image这两个库。
以及Qt（Qt算是开发环境吧，我也说不清楚）。
